name: Release Workflow

on:
  pull_request:
    branches:
      - main
    types: [closed]

    jobs:
      tag-and-release:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') # Only run if PR is merged and it's from a release branch
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: Setup Node
            uses: actions/setup-node@v2
            with:
              node-version: '21'

          - name: Install conventional-changelog-cli
            run: npm install -g conventional-changelog-cli

          - name: Generate Release Notes
            run: conventional-changelog -p angular -i CHANGELOG.md -s && git add CHANGELOG.md

          - name: Commit and Push Changes
            run: |
              git config user.name github-actions
              git config user.email github-actions@github.com
              git commit -m "chore: update changelog" || echo "No changes to commit"
              git push
          - name: Create GitHub Release
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              VERSION_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
              gh release create $VERSION_TAG CHANGELOG.md --title "Release $VERSION_TAG" --notes-file CHANGELOG.md